package ru.app.command;

import java.sql.SQLException;
import java.time.ZonedDateTime;
import ru.app.collection.Collection;
import ru.app.db.DatabaseManager;
import ru.app.network.Request;
import ru.app.object.Product;

/**
 * Command to add a new product to the collection.
 *
 * <p>The product {@code id} is generated by the PostgreSQL sequence. The operation is performed
 * within a database transaction: the product is inserted into the database first, and only on
 * success is it added to the in-memory collection. If either step fails, the transaction is rolled
 * back.
 */
public class AddCommand extends AbstractCommand {
  private final DatabaseManager dbManager;

  /**
   * Creates a new AddCommand.
   *
   * @param dbManager the database manager for persisting the product
   */
  public AddCommand(DatabaseManager dbManager) {
    this.dbManager = dbManager;
  }

  @Override
  public String getName() {
    return "add";
  }

  @Override
  public CommandResult execute(Request request, Collection collection) {
    Product product = request.product();
    if (product == null) return CommandResult.error("No product data provided");

    Product productToInsert =
        new Product(
            null,
            product.name(),
            product.coordinates(),
            product.price(),
            product.partNumber(),
            product.unitOfMeasure(),
            product.owner(),
            ZonedDateTime.now(),
            null);

    try {
      dbManager.beginTransaction();
      Integer generatedId = dbManager.insertProduct(productToInsert, request.login());
      Product productWithId =
          new Product(
              generatedId,
              product.name(),
              product.coordinates(),
              product.price(),
              product.partNumber(),
              product.unitOfMeasure(),
              product.owner(),
              productToInsert.creationDate(),
              request.login());
      try {
        collection.add(productWithId);
      } catch (IllegalArgumentException e) {
        dbManager.rollback();
        return CommandResult.error("Failed to add product: " + e.getMessage());
      }
      dbManager.commit();
      return CommandResult.success("Product added with id=" + generatedId);
    } catch (SQLException e) {
      dbManager.rollback();
      return CommandResult.error("Failed to add product: " + e.getMessage());
    } catch (IllegalArgumentException e) {
      dbManager.rollback();
      return CommandResult.error(e.getMessage());
    }
  }
}
