package ru.app.object;

import java.io.Serial;
import java.io.Serializable;
import java.time.ZonedDateTime;

/**
 * Product stored in the collection.
 *
 * <p>Contains all product attributes including name, coordinates, price, part number, unit of
 * measure, owner information, creation date, and the login of the user who created the product.
 * Products are compared and sorted by {@code id} in natural order.
 *
 * <p>Implements {@link Serializable} for network transmission and {@link Comparable} for ordering
 * in the priority queue.
 *
 * @param id identifier (must be {@code null} or {@code > 0}); generated by the server
 * @param name name (must not be {@code null} or empty)
 * @param coordinates coordinates (must not be {@code null})
 * @param price price (may be {@code null}; if present, must be {@code > 0} and finite)
 * @param partNumber part number (must not be {@code null}, length 22–83 characters)
 * @param unitOfMeasure unit of measure (must not be {@code null})
 * @param owner owner (must not be {@code null})
 * @param creationDate creation date (must not be {@code null})
 * @param createdBy login of the user who created this product (may be {@code null} until assigned
 *     by server)
 */
public record Product(
    Integer id,
    String name,
    Coordinates coordinates,
    Float price,
    String partNumber,
    UnitOfMeasure unitOfMeasure,
    Person owner,
    ZonedDateTime creationDate,
    String createdBy)
    implements Comparable<Product>, Serializable {

  @Serial private static final long serialVersionUID = 1L;

  /**
   * Creates a product with validation of all fields according to domain constraints.
   *
   * @param id identifier (must be {@code null} or {@code > 0})
   * @param name name (must not be {@code null} or empty)
   * @param coordinates coordinates (must not be {@code null})
   * @param price price (may be {@code null}; if present, must be {@code > 0} and finite)
   * @param partNumber part number (must not be {@code null}, length 22–83 characters)
   * @param unitOfMeasure unit of measure (must not be {@code null})
   * @param owner owner (must not be {@code null})
   * @param creationDate creation date (must not be {@code null})
   * @param createdBy login of the user who created this product (may be {@code null} until assigned
   *     by server)
   * @throws IllegalArgumentException if any field fails validation
   */
  public Product(
      Integer id,
      String name,
      Coordinates coordinates,
      Float price,
      String partNumber,
      UnitOfMeasure unitOfMeasure,
      Person owner,
      ZonedDateTime creationDate,
      String createdBy) {
    if (id != null && id <= 0) throw new IllegalArgumentException("'id' can't be <= 0.");
    this.id = id;

    if (name == null) throw new IllegalArgumentException("'name' can't be null.");
    if (name.isEmpty()) throw new IllegalArgumentException("'name' can't be empty.");
    this.name = name;

    if (coordinates == null) throw new IllegalArgumentException("'coordinates' can't be null");
    this.coordinates = coordinates;

    if (creationDate == null) throw new IllegalArgumentException("'creationDate' can't be null");
    this.creationDate = creationDate;

    if (price != null && (price <= 0 || !Float.isFinite(price)))
      throw new IllegalArgumentException("'price' must be > 0");
    this.price = price;

    if (partNumber == null) throw new IllegalArgumentException("'partNumber' can't be null.");
    if (partNumber.length() < 22)
      throw new IllegalArgumentException("'partNumber' length must be >= 22.");
    if (partNumber.length() > 83)
      throw new IllegalArgumentException("'partNumber' length can't be > 83.");
    this.partNumber = partNumber;

    if (unitOfMeasure == null) throw new IllegalArgumentException("'unitOfMeasure' can't be null.");
    this.unitOfMeasure = unitOfMeasure;

    if (owner == null) throw new IllegalArgumentException("'owner' can't be null");
    this.owner = owner;

    this.createdBy = createdBy;
  }

  /**
   * Compares this product with another by {@code id}.
   *
   * @param other another product to compare with
   * @return negative, zero, or positive number if this id is less than, equal to, or greater than
   *     the other id respectively
   */
  @Override
  public int compareTo(Product other) {
    return this.id.compareTo(other.id);
  }
}
